### ISSUE TITLE
Describir cómo el grupo se conforma como instrumento legal (Empresa, Socios, CEO, Empleados) y si tendrán un contrato con que cláusulas.

### ISSUE THREAD

**Issue by Franco-Arce** [Winnie-The-POO-ARGBroker/ARGBroker-Demo#13]

**Comment by MagaBechis** [comment]
Describir cómo el grupo se conforma como instrumento legal (Empresa, Socios, CEO,
Empleados) y si tendrán un contrato con que cláusulas.

 Contrato de constitución de sociedad

Cláusula 1: CONFORMACIÓN: El grupo se conformará legalmente como una Sociedad Comercial, más precisamente como una sociedad anónima, la cual estará radicada en la Ciudad de Córdoba Capital y será inscrita bajo la denominación “ARGBroker” (Ley de sociedades comerciales Ley N°19.550)

Cláusula 1.1: OBJETIVO: El objetivo común de la sociedad es desarrollar y operar una aplicación innovadora y segura que facilite las transacciones entre inversores, con el fin de ofrecer a nuestros usuarios una experiencia eficiente y rentable.

Cláusula 1.2: PACTO DE SOCIOS: El pacto de socios es válido desde el 23 de mayo de 2024 hasta 23 de diciembre de 2024.

Cláusula 1.3: SOCIOS y ROLES: La sociedad estará conformada por los siguientes socios:
Socio 1: Herman Aguilar Tinel mayor de edad 35 años, con DNI 34.349.529, se encargará de la parte de programación y cumplirá el rol de operario de programación. 
Socio 2: Erica Fernandez mayor de edad 43 años, con DNI 27.895.483, se encargará de la parte de ética y cumplirá el rol de operario de ética.
Socio 3: Eliana Di Lorenzo Vera, mayor de edad 21 años, con DNI 44.134.646, se encargará de la parte de programación y cumplirá el rol de coordinadora en programación.
Socio 4: Gianna Giavarini mayor de edad 26 años, con DNI 40.723.354, se encargará de la parte de base de datos y cumplirá el rol de operario de base de datos.
Socio 5: Hector Gabriel Burgos, mayor de edad 24 años, con DNI 42.218.943, se encargará de la parte de ética y cumplirá el rol de coordinador de ética.
Socio 6: Franco Gonzalo Arce, mayor de edad 21 años, con DNI 44.577.669, se encargará de la parte de base de datos y cumplirá el rol de coordinador de base de datos.
Socio 7: Magali Maylén Bechis mayor de edad 19 años, con DNI 46.128.548, se encargará de la parte de ética y cumplirá el rol de operaria de ética. 

Cláusula 1.4: RESPONSABILIDADES: Cada integrante de la sociedad asumirá roles y responsabilidades específicas en el área que le es asignada, de acuerdo a sus habilidades y experiencia, comprometiéndose a trabajar de manera colaborativa y a brindar apoyo mutuo en todas las tareas necesarias para el funcionamiento y crecimiento.
Cláusula 1.5: TOMA DE DECISIONES: En lo que respecta a la toma de decisiones de la empresa, se establecerán procedimientos claros, de manera eficiente y efectiva. En asuntos críticos para la empresa, las decisiones importantes serán tomadas por consenso entre todos los socios. En asuntos que correspondan a un área en particular, las decisiones las tomarán por consenso los integrantes de dicha área.
Cláusula 1.6: CONFIDENCIALIDAD: Cada integrante de la sociedad se compromete a mantener la confidencialidad de la información sensible de la empresa, incluyendo datos de los usuarios, estrategias de negocio, técnicas de programación, líneas de código, entre otros.
Cláusula 1.7: RESOLUCIÓN DE CONFLICTOS: Si surge algún conflicto entre los socios, la resolución deberá realizarse de manera dialogada y constructiva, buscando siempre el interés común de la empresa.
