### ISSUE TITLE
Describir quiénes y ante quien deben matricularse a nivel provincial para ejercer la Profesión.

### ISSUE THREAD

**Issue by Franco-Arce** [Winnie-The-POO-ARGBroker/ARGBroker-Demo#14]
Considerando los datos necesarios para cumplir con las funcionalidades especificadas.

**Comment by MagaBechis** [comment]
Describir quiénes y ante quien deben matricularse a nivel provincial para ejercer la
Profesión.
Cláusula 2: MATRICULACIÓN: Cada socio y dependiente de la sociedad que cumpla tareas del área informática deberá  estar  matriculado por ante el Consejo Profesional de Ciencias Informáticas de la Provincia de Córdoba (C.P.C.I.P.C.) y cumplir con los requisitos exigidos por la ley 7642.
