### ISSUE TITLE
Describir que requerimientos deben cumplir el código programado y las bases de datos según la legislación vigente

### ISSUE THREAD

**Issue by Franco-Arce** [Winnie-The-POO-ARGBroker/ARGBroker-Demo#15]

**Comment by MagaBechis** [comment]
Describir que requerimientos deben cumplir el código programado y las bases de
datos según la legislación vigente
Cláusula 3: REQUERIMIENTOS DEL CÓDIGO PROGRAMADO Y LAS BASES DE DATOS: 
1 Protección de datos personales: El código programado y las bases de datos deben cumplir con la normativa de protección de datos personales, garantizando la confidencialidad y seguridad de la información personal de los usuarios.
2 Cumplimiento de regularizaciones financieras: El código programado y las bases de datos deben cumplir con las regulaciones financieras vigentes, incluyendo normativas sobre transacciones financieras, protección al inversor, prevención del lavado de dinero, entre otras.
3 Seguridad informática: Se deben implementar medidas de seguridad informática adecuadas para proteger la integridad de los datos y prevenir posibles ciberataques.
4 Registro de actividades: Es importante llevar un registro detallado de las actividades realizadas en la plataforma, tanto en lo que respecta a las transacciones financieras como a las interacciones de los usuarios.
5 Cumplimiento de normativas de la Bolsa de Valores: El código programado y las bases de datos deben cumplir con las normativas y requerimientos específicos de la Bolsa de Valores de Buenos Aires (MERVAL) en lo que respecta a la intermediación bursátil.
Respecto y bajo las leyes: Protección de los datos personales Ley  N° 25.326, Ley de Mercado de Capitales Ley N° 26.831 y bajo las normativas de la comisión Nacional de Valores(CNV) y las normativas de la bolsa de valores de Buenos Aires (MERVAL).
