### ISSUE TITLE
Enumerar los pasos para que ARGBroker sea parte del Registro Nacional de software.

### ISSUE THREAD

**Issue by Franco-Arce** [Winnie-The-POO-ARGBroker/ARGBroker-Demo#16]

**Comment by MagaBechis** [comment]
Enumerar los pasos para que ARGBroker sea parte del Registro Nacional de
software.
Cláusula 4: PASOS A SEGUIR PARA INSCRIBIR A ARGBROKER AL REGISTRO EN EL REGISTRO NACIONAL DE SOFTWARE: 
Realizar una búsqueda de antecedentes para verificar la originalidad del software.
Solicitar la protección del software a través del registro de Propiedad Intelectual en la Administración Nacional de Derechos de Autor (ANDA).
Completar el formulario de registro con la información requerida sobre el software.
Pagar la tasa correspondiente al registro.
Presentar la documentación requerida en la oficina de Propiedad Intelectual.
Los requisitos que debemos cumplir son:
Cumplir con los requisitos técnicos y legales establecidos por el Registro Nacional de la Propiedad Intelectual, ley 11.723.
Ser titular de los derechos de autor del software a registrar.
Adjuntar una copia del código fuente del software o una descripción detallada del mismo.
No haber registrado previamente el software en otro registro nacional o internacional.
Aceptar y cumplir con las normativas de protección de derechos de autor y propiedad intelectual en Argentina.
