### ISSUE TITLE
Si un integrante del grupo no realiza el trámite de matriculación, que pena le corresponde a nivel provincial.

### ISSUE THREAD

**Issue by Franco-Arce** [Winnie-The-POO-ARGBroker/ARGBroker-Demo#17]

**Comment by HermanAguilar** [comment]
Para el caso en que un integrante de la empresa no esté matriculado, los restantes integrantes emplazarán por 5 días al incumplidor para que inicie el trámite de matriculación y en caso en que continúe incumpliendo se hará la denuncia ante el C.P.C.I.P.C. por incumplimiento del art. 6 de la Ley Provincial N° 7642, que establece una multa en pesos argentinos que oscilara entre diez (10) o quinientas veces (500) el valor del derecho de inscripción a la matricula
Por ejemplo si la socia Erica Fernandez, decide no matricularse, la convocamos a una reunión para indicarle que inicie el trámite de su matriculación para poder seguir en el proyecto ARGBroker, si continúa incumpliendo, se le enviará una carta de documento al domicilio y si continúa en la negativa se procederá a la desvinculación del proyecto y la puesta en conocimiento al Consejo Profesional de Ciencias Informáticas de la Provincia de Córdoba.
