### ISSUE TITLE
Si un integrante del grupo divulga los datos de la base de datos interna, describir como legalmente deberían accionar los demás.

### ISSUE THREAD

**Issue by Franco-Arce** [Winnie-The-POO-ARGBroker/ARGBroker-Demo#19]

**Comment by GabyBoom** [comment]
Si un integrante del grupo divulga los datos de la base de datos interna, describir
como legalmente deberían accionar los demás.

Cláusula 7: DIVULGACIÓN DE DATOS DE LA BASE DE DATOS POR PARTE DE UN INTEGRANTE DEL GRUPO.
Pasos para tomar medidas tras la divulgación de datos:  
Detener la divulgación: Tomar medidas urgentes para que la divulgación de datos no se agrave. Por ejemplo: bloquear el acceso del integrante a la base de datos, cambiar contraseñas, quitarle el permiso del correo de la empresa, entre otros. 
 
Notificar a los clientes: Avisar a las personas afectadas sobre divulgación de datos. Es recomendable que sean transparentes con sus clientes y que les avisen sobre cualquier incidente que pueda poner en riesgo su información. 
 
Realizar copias de seguridad: para recuperar los datos ante una incidencia, impidiendo la pérdida de los datos y permitiendo la recuperación de la normalidad en el trabajo. 
 
Investigar la infracción: para determinar el alcance de la divulgación, el tipo de información divulgada y las posibles motivaciones del integrante del grupo.  Debe documentarse adecuadamente. 
 
Evaluar los daños: tanto los cualitativos y cuantitativos con la respectiva notificación a las personas y/o clientes afectados.


 
Tomar medidas contra el integrante: reprimenda verbal o escrita, una suspensión, una reducción de sueldo o incluso el despido (Dependerá de la gravedad del asunto). 
 
Acciones legales: pueden incluir una demanda civil para obtener una indemnización por los daños causados, así como una denuncia penal para que el integrante del grupo sea juzgado por el delito.


Implementar medidas preventivas: Para evitar que se repitan este tipo de incidentes. Estas medidas pueden incluir:  
Revisar y actualizar las políticas de seguridad de la información de la empresa. 
Capacitar a los empleados sobre la importancia de la protección de datos. 
Implementar controles de acceso más estrictos a la base de datos interna. 
Utilizar software de seguridad adicional para proteger la base de datos.
