### ISSUE TITLE
Si otro integrante del grupo reutiliza el código para fines personales, describir como legalmente deberían accionar los demás según la Legislación de la Provincia de Córdoba y el Código Penal Argentino.

### ISSUE THREAD

**Issue by Franco-Arce** [Winnie-The-POO-ARGBroker/ARGBroker-Demo#20]

**Comment by GabyBoom** [comment]
integrante del grupo reutiliza el código para fines personales, describir como legalmente
deberían accionar los demás según la Legislación de la Provincia de Córdoba y el
Código Penal Argentino.

Clausula 8: Si otro integrante del grupo reutiliza el código para fines personales, describir como legalmente deberían accionar los demás según la Legislación de la Provincia de Córdoba y el Código Penal Argentino.

Para el caso que un integrante del grupo, por ejemplo, Magali Maylen Bechis, reutilice el código sin la debida autorización, los demás integrantes de la empresa ARGBroker, pueden tomar las siguientes medidas: 
  
Considerar excluir a la persona del cargo antes de iniciar acciones legales, ayudará a proteger sus derechos y a prevenir que la persona cause más daño 
 
Guardar una copia del código en un lugar seguro y accesible solo para los miembros del grupo, esto permitirá mostrar que son propietarios del código. 
 
Recopilar pruebas: El primer paso es recopilar pruebas que demuestren que el miembro del grupo ha utilizado el código de manera indebida. Se pueden incluir:  
Capturas de pantalla del código reutilizado 
Correos electrónicos o mensajes de chat, donde el miembro del Grupo admite haber reutilizado el código.   
Testimonios de otros miembros del grupo que puedan corroborar el uso indebido del Código.  
Registrar fecha y hora en el que se descubrió el uso indebido del Código.  
Presentar una denuncia: cuando se reúnan las pruebas, los miembros del grupo afectado pueden presentar una denuncia ante las autoridades competentes en Córdoba las denuncias por apropiación indebida e incidencia se pueden presentar ante:  
La policía: puede iniciar una investigación, si se encuentran pruebas suficientes, remitirá el caso a la justicia penal. (no es recomendable entregar evidencia a la policía directamente si es un caso de código reutilizado indebidamente). En este tipo de situaciones, la evidencia digital puede ser muy frágil y susceptible de manipulación.) 
Unidad de Cibercrimen de la ciudad de córdoba: se especializa en la investigación de delitos informáticos, incluyendo el robo de información digital. 
El fiscal:  puede recibir denuncias y decidir si inicia una investigación penal. 
Un juez: en algunos casos los miembros del grupo afectado pueden presentar una denuncia directamente al juez. 
 
Buscar asesoramiento legal: Es recomendable buscar un abogado especializado en la materia. 
 
Iniciar un proceso civil: además de presentar una denuncia penal, los miembros del grupo afectado también pueden iniciar un proceso civil contra el miembro del grupo que reutilizo el código indebidamente (En un proceso civil, el miembro del grupo afectado puede solicitar una indemnización por los daños y perjuicios que le haya causado el uso indebido del código.) 
 
 
ARTICULO 173 
16. El que defraudare a otro mediante cualquier técnica de manipulación informática que altere el normal funcionamiento de un sistema informático o la transmisión de datos. (Inciso incorporado por art. 9° de la Ley N° 26.388, B.O. 25/6/2008).
