### ISSUE TITLE
Si otro integrante del grupo reutiliza el código para fines personales a nivel internacional, describir qué instrumento legal respalda a ARGBroker.

### ISSUE THREAD

**Issue by Franco-Arce** [Winnie-The-POO-ARGBroker/ARGBroker-Demo#21]

**Comment by GabyBoom** [comment]
Si otro integrante del grupo reutiliza el código para fines personales a nivel
internacional, describir qué instrumento legal respalda a ARGBroker.

Cláusula 9: Si otro integrante del grupo reutiliza el código para fines personales a nivel internacional, describir qué instrumento legal respalda a ARGBroker
El instrumento legal a nivel internacional que respalda a ARGBroker es el Convenio de Berna para la Protección de las Obras Literarias y Artísticas (1886), que protege obras literarias y artísticas, incluyendo el software. 
Derechos exclusivos del autor: reproducción, comunicación pública, traducción y adaptación. 
Reutilización no autorizada del código podría ser una violación. 
ARGBroker puede tomar medidas legales: carta de cese y desistimiento, demanda judicial, acciones penales. 
Limitaciones: ideas y principios no protegidos, excepciones para fines educativos o de investigación. 
Tratado de la OMPI sobre Derecho de Autor (WCT): 
Actualiza y complementa el Convenio de Berna para la era digital: 
Protege programas de computadora y bases de datos. 
Combate la elusión de medidas de protección (cifrado). 
Protege la información sobre la gestión de derechos (autoría, fecha). 
Armoniza derechos de distribución y alquiler. 
Amplía el derecho de comunicación pública (transmisión digital). 
Es importante para América latina ya que fortalece la protección de derechos de autor en el entorno digital. 
 
Acuerdo sobre los Aspectos de los Derechos de Propiedad Intelectual relacionados con el Comercio (ADPIC) (1994): 
Es un tratado internacional que forma parte de la Organización Mundial del Comercio (OMC). Establece normas mínimas para proteger la propiedad intelectual en los países miembros de la OMC. 
Protege el ADPIC: 
Derechos de autor, Patentes, Marcas, Indicaciones geográficas, Diseños industriales, Secretos comerciales. 
 
Obligaciones:  
Los países deben proteger la propiedad intelectual y dar igual trato a todos. 
 
Estos instrumentos reconocen a los autores de software el derecho exclusivo de autorizar o prohibir la reproducción, la comunicación al público, la distribución, el alquiler, la traducción, la adaptación y la transformación de sus obras.
