### ISSUE TITLE
Si la base de datos es adulterada de manera externa, a nivel nacional, describir qué instrumento legal respalda a ARGBroker.

### ISSUE THREAD

**Issue by Franco-Arce** [Winnie-The-POO-ARGBroker/ARGBroker-Demo#22]

**Comment by EricaFerArg** [comment]
Si la base de datos está adulterada de manera externa, a nivel nacional, describa qué instrumento legal respalda a ARGBroker.


Cláusula 10: Si la base de datos es adulterada de manera externa, a nivel nacional, describir qué instrumento legal respalda a ARGBroker
El instrumento legal con que cuenta la empresa para el caso de que la base de datos sea adulterada de manera externa es el Código Penal que en su Art. 183, donde describe la figura del Daño, el segundo párrafo de dicho artículo específicamente dispone que el que alterare, destruyere o inutilizare datos, documentos, programas o sistemas informáticos incurrirá en la pena del delito de Daño que establece una prisión de 15 días a 1 año.
