### ISSUE TITLE
Cuando los programadores de ARGBroker incurren en una negligencia, a que instrumento legal se acude y quien.

### ISSUE THREAD

**Issue by Franco-Arce** [Winnie-The-POO-ARGBroker/ARGBroker-Demo#24]

**Comment by EricaFerArg** [comment]
Cuando los programadores de ARGBroker incurren en una negligencia, a que instrumento legal se acude y quien. 

Cláusula 12: Cuando los programadores de ARGBroker incurren en una negligencia, a que instrumento legal se acude y quien.
El principal instrumento legal para el caso de negligencia por parte de por ejemplo, Gabriel Burgos Profesional de Informática e integrante de ARGBroker, es la denuncia ante el Tribunal Arbitral y de Disciplina del C.P.C.I.P.C., pudiendo realizarlo el cliente, los colegas en función de art. 21 de la ley 7642 y toda otra persona que se vea afectada por dicho obrar negligente.
