### ISSUE TITLE
Cómo ARGBroker debe implementar seguridad según la Ley de Protección de Datos Personales.

### ISSUE THREAD

**Issue by Franco-Arce** [Winnie-The-POO-ARGBroker/ARGBroker-Demo#25]

**Comment by EricaFerArg** [comment]
Cómo ARGBroker debe implementar seguridad según la Ley de Protección de Datos
Personales.

Cláusula 13: Cómo ARGBroker debe implementar seguridad según la Ley de Protección de Datos Personales.
Según la ley de datos personales en su  ARTÍCULO 9°(Seguridad de los datos), determina:
1. El responsable o usuario del archivo de datos debe adoptar las medidas técnicas y organizativas que resulten necesarias para garantizar la seguridad y confidencialidad de los datos personales, de modo de evitar su adulteración, pérdida, consulta o tratamiento no autorizado, y que permitan detectar desviaciones, intencionales o no, de información, ya sea que los riesgos provengan de la acción humana o del medio técnico utilizado.
2. Queda prohibido registrar datos personales en archivos, registros o bancos que no reúnan condiciones técnicas de integridad y seguridad.
Por lo tanto ARGBroker debería de implementar medidas técnicas y organizativas adecuadas para garantizar la seguridad y confidencialidad de datos como por ejemplo: 
Acceso  autorizado: limita el acceso solo a empleados o terceros autorizados.
Cifrado de datos: utilizar un cifrado robusto para la protección de los datos.
Seguridad en la red: implementar medidas para proteger contra accesos no autorizados.
Auditorías: realizar auditorías para verificar que las medidas de seguridad estén funcionando correctamente.
Capacitación del personal: para que entiendan la importancia de mantener la seguridad y confidencialidad de los datos.
Política de privacidad y consentimiento: Establecer una política clara y transparente que informe a los individuos como se manejan sus datos.
