### ISSUE TITLE
Si el cliente decide reemplazar a ARGBroker por otro proveedor, describir cómo se debe actuar de manera ética ante el cliente y los colegas

### ISSUE THREAD

**Issue by Franco-Arce** [Winnie-The-POO-ARGBroker/ARGBroker-Demo#26]

**Comment by HermanAguilar** [comment]
Para el caso en que un cliente decida reemplazar a la empresa ARGBroker por otro proveedor, es importante tener en cuenta que todos los profesionales de Informática deben promover la cooperación y las buenas relaciones entre los integrantes de la profesión y no deben desacreditar ni injuriar a colegas. Puntualmente para el caso de reemplazo en la tarea como el mencionado, el profesional saliente deberá proporcionar amplia y detallada información de la misma al profesional o profesionales que tomarán su cargo.
En cuanto al cliente, el profesional de Informática además de atender con la mayor objetividad, diligencia y probidad posible los asuntos de su cliente es obligación ética el secreto profesional.
