### ISSUE TITLE
Si un usuario denuncia a ARGBroker por divulgación de sus datos personales, a que legislación recurrió el mismo y como ARGBroker puede respaldarse jurídicamente.

### ISSUE THREAD

**Issue by Franco-Arce** [Winnie-The-POO-ARGBroker/ARGBroker-Demo#27]

**Comment by HermanAguilar** [comment]
El usuario recurrió a la ley 25.326 referida a la Protección de Datos Personales.
Ahora bien ARGBroker, como respaldo jurídico, puede explicar que al ser una empresa de intermediación financiera, bajo ninguna condición divulgará datos personales de los usuarios, salvo que los mismos sean requeridos por orden judicial, por el BCRA en ejercicio de sus funciones o por organismos recaudadores de impuestos nacionales, provinciales o municipales.  (art. 5 inc. 2 apartado e) de la ley 25326)
